// ГРЕЙД ДОСТИЖЕНИЯ (BACKLOG 44.12, владелец 2026-10-07: «иконки у всех слишком одинаковые, оформление по грейду»): у КАЖДОГО достижения свой
// грейд (те же пять уровней, что у редкости наград) и своя иконка внутри лесенки. Грейд — про трудность САМОГО достижения, а не про награду:
// у награды своя редкость (rewards.ts, `rewardRarity`), её не путать. Таблицы явные: новое достижение без грейда и иконки не проходит тест.
import type { Rarity } from './rewards'

// Правило: «первые шаги» — обычные; лесенка из четырёх ступеней идёт обычное → необычное → редкое → эпическое; самые трудные вершины
// (сто дней серии, сто идеальных дней, тысяча баллов, 250 тренировочных дней) — легендарные.
export const GRADE: Record<string, Rarity> = {
  first_metric: 'common',
  first_weight: 'common',
  first_goal: 'common',
  first_skill: 'common',
  first_book: 'common',
  first_workout: 'common',
  streak_5: 'common',
  streak_10: 'uncommon',
  streak_30: 'rare',
  streak_100: 'legendary',
  perfect_days_1: 'common',
  perfect_days_10: 'uncommon',
  perfect_days_30: 'rare',
  perfect_days_100: 'legendary',
  points_100: 'common',
  points_500: 'rare',
  points_1000: 'legendary',
  workouts_10: 'uncommon',
  workouts_50: 'rare',
  workouts_100: 'epic',
  workouts_250: 'legendary',
  challenges_1: 'common',
  challenges_5: 'uncommon',
  challenges_10: 'rare',
  challenges_25: 'epic',
  goals_10: 'uncommon',
  goals_25: 'rare',
  goals_50: 'epic',
  skills_5: 'uncommon',
  skills_10: 'rare',
  skills_25: 'epic',
  books_5: 'uncommon',
  books_10: 'rare',
  books_25: 'epic',
  milestones_1: 'common',
  milestones_5: 'uncommon',
  milestones_10: 'rare',
  milestones_25: 'epic',
  words_10: 'common',
  words_25: 'uncommon',
  words_50: 'rare',
  words_100: 'epic',
  learned_10: 'common',
  learned_25: 'uncommon',
  learned_50: 'rare',
  learned_100: 'epic',
  mega_productivity: 'epic',
}

// Грейд СКРЫТЫХ достижений (hiddenAchievements.ts, BACKLOG 49.1) — отдельно от GRADE: те таблицы описывают только видимые достижения (тесты сверяют их с реестром).
export const HIDDEN_GRADE: Record<string, Rarity> = {
  secret_year: 'legendary',
  secret_perfect_200: 'legendary',
  secret_points_5000: 'legendary',
  secret_marks_1000: 'epic',
  secret_weight_100: 'epic',
  secret_all_rounder: 'epic',
  secret_mega_3: 'epic',
  secret_words_500: 'legendary',
  secret_workouts_500: 'legendary',
  secret_milestones_100: 'legendary',
}

export const gradeOf = (key: string): Rarity => GRADE[key] ?? HIDDEN_GRADE[key] ?? 'common'

// Иконка КАЖДОГО достижения (имена из lib/icons.ts): внутри одной лесенки все разные, по смыслу ступени.
export const ICON_BY_KEY: Record<string, string> = {
  first_metric: 'done',
  first_weight: 'scale',
  first_goal: 'goals',
  first_skill: 'skills',
  first_book: 'book',
  first_workout: 'dumbbell',
  streak_5: 'flame',
  streak_10: 'zap',
  streak_30: 'mountain',
  streak_100: 'trophy',
  perfect_days_1: 'star',
  perfect_days_10: 'sparkles',
  perfect_days_30: 'medal',
  perfect_days_100: 'party',
  points_100: 'coin',
  points_500: 'wallet',
  points_1000: 'piggybank',
  workouts_10: 'run',
  workouts_50: 'plate',
  workouts_100: 'boxing',
  workouts_250: 'medal',
  challenges_1: 'challenges',
  challenges_5: 'jumprope',
  challenges_10: 'trophy',
  challenges_25: 'medal',
  goals_10: 'checklist',
  goals_25: 'compass',
  goals_50: 'trophy',
  skills_5: 'wrench',
  skills_10: 'paintbrush',
  skills_25: 'music',
  books_5: 'note',
  books_10: 'study',
  books_25: 'bulb',
  milestones_1: 'milestones',
  milestones_5: 'pin',
  milestones_10: 'hourglass',
  milestones_25: 'compass',
  words_10: 'english',
  words_25: 'note',
  words_50: 'list',
  words_100: 'hash',
  learned_10: 'brain',
  learned_25: 'bulb',
  learned_50: 'study',
  learned_100: 'sparkles',
  mega_productivity: 'pulse',
}
